import React, { createContext } from "react";
import BarChart from '@/components/BarChart';
// import Calendar from 'react-calendar';
import Header from '@/components/Header';
import RecentOrders from '@/components/UpcomingVacation';
import TopCards from '@/components/TopCards';
import Head from 'next/head';

const employees = [
  {
    name: {
      first: 'Nick',
      last: 'Abell',
    },
    id: 1,
    shift: '2cnd',
    position: 'Clerk',
    vacationTotal: 180,
    vactionRemaining: 120,
    points: -2,
    seniorityDate: 11,
  },
  {
    name: {
      first: 'Bob',
      last: 'Smith',
    },
    id: 2,
    position: 'Clerk',
    shift: '2cnd',
    vacationTotal: 180,
    vactionRemaining: 10,
    points: -8,
  },
  {
    name: {
      first: 'Alexa',
      last: 'Amalia',
    },
    id: 6,
    position: 'Fork Lift',
    shift: '2cnd',
    vacationTotal: 120,
    vactionRemaining: 90,
    points: 4,
  },
  {
    id: 5,
    shift: '1st',
    name: {
      first: 'Mirabelle',
      last: 'Martinez',
    },
    vacationTotal: 180,
    vactionRemaining: 80,
    points: 0,
    date: 'Now'
  },
  {
    id: 3,
    shift: '3rd',
    name: {
      first: 'Aubry',
      last: 'Williams',
    },
    vacationTotal: 180,
    vactionRemaining: 80,
    points: 0,
    total: 6969.69,
    method: 'Paypal',
    date: 'Now'
  },
]

export const DataContext = createContext(employees);
// const [shift, setShift] = useState('2cnd');

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DataContext.Provider value={employees}>
        <main className='bg-gray-600 min-h-screen'>
          <Header />
          <TopCards />
          <div className='grid p-4 md:grid-cols-3 grid-cols-1 gap-4'>
            <BarChart />
            <RecentOrders />
          </div>
        </main>
      </DataContext.Provider>
    </>
  )
}
